views/company.py
from ..forms import CreateWorkForm
from ..models import Job
from ..share import db, mail
from flask import render_template, request, Blueprint, flash
from flask_mail import Message

company = Blueprint('company', __name__)


@company.route("/create", methods=['GET', 'POST'])
def create_job():
    form = CreateWorkForm()

    if request.method == "POST":
        if form.validate() == False:
            return render_template("create_job.html", form=form)
        else:
            new_job = Job()
            new_job.title = form.title.data.lower() + "/ %s" % form.company_name.data
            new_job.link = form.link.data
            new_job.location = form.location.data.lower()
            new_job.description = form.description.data
            new_job.source = "company"
            new_job.sponsor = 1
            new_job.company_name = form.company_name.data
            new_job.expire_day = form.expire_day.data

            db.session.add(new_job)
            db.session.commit()

            msg = Message("New Job have been created", sender="ziliot.info@gmail.com", recipients=["info@ziliot.com"])
            msg.body = """
                New Job have been created by
                %s Company
                title : %s
                location : %s
                description : %s
            """ % (new_job.company_name, new_job.title, new_job.location, new_job.description)
            mail.send(msg)

            flash("Create Job Success")
            return render_template("create_job.html", form=form)

    if request.method == "GET":
        return render_template("create_job.html", form=form)

views/estonia.py
from ..forms import SearchForm
from ..models import JobEstonia
from flask import render_template, request, redirect, url_for, Blueprint

JOB_PER_PAGE = 7

estonia = Blueprint('estonia', __name__)

@estonia.route("/en", methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if request.method == "POST":
        if form.title.data == "":
            title = "all"
        else:
            title = form.title.data.lower().strip()
        if form.location.data == "":
            location = "everywhere"
        else:
            location = form.location.data.lower().strip()
        return redirect(url_for('estonia.result', title=title, location=location, page=1, lang="ee"))
    elif request.method == "GET":
        return render_template("searcher.html", form=form, lang="ee")

@estonia.route('/en/<string:title>-jobs-in-<string:location>')
@estonia.route('/en/<int:page>/<string:title>-jobs-in-<string:location>')
def result(title, location, page=1):
    form = SearchForm()
    job_obj = JobEstonia()
    job_list = job_obj.get_job(title, location).paginate(page, JOB_PER_PAGE, False)
    return render_template("results.html", jobs=job_list, title=title.title(), location=location.title(), form=form, lang="ee")

# Estonia pages
@estonia.route('/', methods=['GET', 'POST'])
@estonia.route("/ee", methods=["GET", "POST"])
def searchEstonia():
    form = SearchForm()
    if request.method == "POST":
        if form.title.data == "":
            title = "all"
        else:
            title = form.title.data.lower().strip()
        if form.location.data == "":
            location = "everywhere"
        else:
            location = form.location.data.lower().strip()
        return redirect(url_for('estonia.resultEstonia', title=title, location=location, page=1, lang="ee"))
    elif request.method == "GET":
        return render_template("searcher_estonia.html", form=form, lang="ee")


@estonia.route('/ee/<string:title>-jobs-in-<string:location>')
@estonia.route('/ee/<int:page>/<string:title>-jobs-in-<string:location>')
def resultEstonia(title, location, page=1):
    form = SearchForm()
    job_obj = JobEstonia()
    job_list = job_obj.get_job(title, location).paginate(page, JOB_PER_PAGE, False)
    return render_template("resultsEstonia.html", jobs=job_list, title=title.title(), location=location.title(), form=form, lang="ee")

@estonia.route("/about")
def about():
    return render_template("about.html")

views/home.py
from ..forms import SearchForm
from ..models import Job
from flask import render_template, request, redirect, url_for, Blueprint

JOB_PER_PAGE = 7

home = Blueprint('home', __name__)

@home.route("/en", methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if request.method == "POST":
        if form.title.data == "":
            title = "all"
        else:
            title = form.title.data.lower().strip()
        if form.location.data == "":
            location = "everywhere"
        else:
            location = form.location.data.lower().strip()
        return redirect(url_for('home.result', title=title, location=location, page=1))
    elif request.method == "GET":
        return render_template("searcher.html", form=form)

@home.route('/en/<string:title>-jobs-in-<string:location>')
@home.route('/en/<int:page>/<string:title>-jobs-in-<string:location>')
def result(title, location, page=1):
    form = SearchForm()
    job_obj = Job()
    job_list = job_obj.get_job(title, location).paginate(page, JOB_PER_PAGE, False)
    return render_template("results.html", jobs=job_list, title=title.title(), location=location.title(), form=form)

# Finnish pages
@home.route('/', methods=['GET', 'POST'])
@home.route("/fi", methods=["GET", "POST"])
def searchFinnish():
    form = SearchForm()
    if request.method == "POST":
        if form.title.data == "":
            title = "all"
        else:
            title = form.title.data.lower().strip()
        if form.location.data == "":
            location = "everywhere"
        else:
            location = form.location.data.lower().strip()
        return redirect(url_for('home.resultFinnish', title=title, location=location, page=1))
    elif request.method == "GET":
        return render_template("searcher_finnish.html", form=form)


@home.route('/fi/<string:title>-jobs-in-<string:location>')
@home.route('/fi/<int:page>/<string:title>-jobs-in-<string:location>')
def resultFinnish(title, location, page=1):
    form = SearchForm()
    job_obj = Job()
    job_list = job_obj.get_job(title, location).paginate(page, JOB_PER_PAGE, False)
    return render_template("resultsFinnish.html", jobs=job_list, title=title.title(), location=location.title(), form=form)

@home.route("/about")
def about():
    return render_template("about.html")
@home.route("/sitemap/page1")
def htmlSiteMap():
    return render_template("/sitemaps/sql_sitemap.html")
@home.route("/sitemap/page2")
def htmlSiteMap2():
    return render_template("/sitemaps/page2_sitemap.html")

templates/create_job.html
{% extends "custom_base.html" %}

{% block page_content %}

<div class="container">
	
	<div class="row">
            <div class="col-xs-2">
            </div>
            <div class="col-xs-8">
                <h2 class="post_h3"> Post jobs or vacancy</h2>

                <form action="{{ url_for('company.create_job') }}" method=post>
                {{form.hidden_tag()}}

            <div class="div_input2">
            {% with flashMessage = get_flashed_messages() %}
            {% if flashMessage %}
                <div class="alert alert-info" role="alert">>{{flashMessage[0]}}</div>
            {% endif %}
            {% endwith %}

            {% for mess in form.title.errors %}
                 <div class="alert alert-danger" role="alert">{{mess}}</div>
            {% endfor %}

             {% for mess in form.location.errors %}
                <div class="alert alert-danger" role="alert">{{mess}}</div>
            {% endfor %}

            {% for mess in form.company_name.errors %}
                <div class="alert alert-danger" role="alert">{{mess}}</div>
            {% endfor %}

             {% for mess in form.description.errors %}
                <div class="alert alert-danger" role="alert">{{mess}}</div>
            {% endfor %}

                {% for mess in form.link.errors %}
                <div class="alert alert-danger" role="alert">{{mess}}</div>
            {% endfor %}

                 {% for mess in form.expire_day.errors %}
                <div class="alert alert-danger" role="alert">{{mess}}</div>
            {% endfor %}

            <h4>Company Name:</h4 >
            <input type="text" id="job_input2" name="company_name" />

            <h4>Job Title:</h4>
            <input type="text" id="job_input2" name="title" />

            <h4>Location:</h4>
            <input type="text" id="job_input2" name="location"/>

            <h4>Link (enter the link to your job page):</h4>
            <input type="text" id="job_input2" name="link" />

            <h4>Description( briefly about job):</h4>
            <textarea id="job_input2" name="description" style="height: 130px;" ></textarea>

            <h4>Expire Day (MM/DD/YYYY):</h4>
            <input type="date" id="job_input2" name="expire_day" />
             <br/>
                <button type="submit" class="btn btn-default">Create Job</button>
            </div>

        </form>
            </div>
            <div class="col-xs-2">
           </div>


            
    </div>
    </div>


{% endblock %}

templates/custom_base.html
{% extends "bootstrap/base.html" %}


{% block head %}
{{ super() }}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/local.css') }}">
<link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">
<link rel="icon" href="/static/img/favicon.ico" type="image/x-icon">

{% endblock %}
	{%- block metas %}
		    <meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Find and apply to {{title}} jobs in {{location}}">
                           <meta name="google-site-verification" content="uM4cfK8P5hmSCa7rWL_x6gKs4utdVpFe48dURukNP90" />
 {%- endblock %}
{% block navbar %}


<div class="row">
        <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                {% if lang == "ee" %}
                        <a class="navbar-brand" href="{{ url_for('estonia.searchEstonia') }}"><span class = "t-brand">  Ziliot </span>  </a>
                {% else %}
            	        <a class="navbar-brand" href="{{ url_for('home.searchFinnish') }}"><span class = "t-brand">  Ziliot </span>  </a>
                {% endif %}
        


                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="collapse">
            	<ul class="nav navbar-nav">
      	            
      	            
                	
                </ul>
                <ul class="nav navbar-nav navbar-right">
                     <li class="dropdown"><a href="#" data-toggle="dropdown"><span class = "t-brand">Countries</span> <span class="caret"></span></a>
                    	<ul class="dropdown-menu">
                            <li><a href="{{url_for('home.searchFinnish')}}">Finland <img class = "count_img"  src="{{ url_for('static', filename='img/fi.png') }}"></a></li>
                            <li><a href="{{url_for('estonia.searchEstonia')}}">Estonia <img class = "count_img"  src="{{ url_for('static', filename='img/ee.png') }}"> </a></li>
                        </ul>
                    </li>
                	<li class="dropdown"><a href="#" data-toggle="dropdown"><span class = "t-brand">Language</span> <span class="caret"></span></a>
                    	<ul class="dropdown-menu">
                            {% if lang == "ee" %}
                                <li><a href="/ee">Estonian<img class = "count_img"  src="{{ url_for('static', filename='img/ee.png') }}"></a></li>
                            {% else %}
                                <li><a href="/fi">Finnish  <img class = "count_img"  src="{{ url_for('static', filename='img/fi.png') }}"></a></li>
                            {% endif %}
                            <li><a href="/en">English <img class = "count_img"  src="{{ url_for('static', filename='img/gb.png') }}"> </a></li>
                        </ul>
                </ul>
            </div>  
        </nav>
    </div>



{% endblock %}

{% block content %}

<div class = "container">
	
	{% block page_content %}
	
	
	{% endblock %}
	
</div>

{% block foot %}

    <footer class="footer">
      <div class="container">
              <ul class="nav navbar-nav">

                    <li><a href="/">Home</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a >Contact</a></li>
                    <li><a >Add CVs</a></li>
                    <li><a href="/create">Post jobs</a></li>
                    <li><a href="/sitemap/page1" class="sr-only"></a></li>
                    <li><a href="/sitemap/page2" class="sr-only"></a></li>
                    <li><a href="/sitemap.xml" class="sr-only"></a></li>


                </ul>
      </div>
    </footer>

{% endblock%}

{% endblock %}

templates/results.html
{% extends "custom_base.html" %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/local.css') }}">

	{% block title %} Find {{title}} jobs in {{location}} {% endblock %}


	{%- block metas %}
		    <meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Find and apply to {{title}} jobs in {{location}}">
    {%- endblock %}

{% block page_content %}

<div class="container">
	
	<div class="row">
		<div class="col-xs-1">
			
			
		</div>
		
		<div class="col-xs-8">
			<div class="r_searcher">

				{% if lang == "ee" %}
					<form action = "{{ url_for('estonia.searchEstonia') }}" method=post>
				{% else %}
						<form action = "{{ url_for('home.search') }}" method=post>
				{% endif %}
				<div class="r_div_input1">
					<label for="r_job_input">What</label>
					<br />
					<input type="text" id="r_job_input" name="title" value="{{title}}"/>
					<span id="input_help">e.g. job, company, title</span>
				</div>
		
				<div class="r_div_input1">
					<label for="r_where_input">Where</label>
					<br />
					<input type="text" id="r_where_input" value="{{location}}" name="location" onfocus="document.getElementById('ui-id-1').style.display='block';" />
					<span id="input_help">e.g. city, country</span>
				</div>
				
				<div class="div_submit1">
					<input type="submit" value="" class="r_subm1" />
				</div>
			</form>
		</div>
			
			
		</div>
		
		<div class="col-xs-3">


		</div>
		
		
		
	</div>


				
		<div class="row">
					
       <div class="col-xs-1">
       	
        	
        	
        </div>

        <div class="col-xs-8">
			{% for job in jobs.items %}
        	<h3 ><a class = "r_title" target="_blank" href="{{job.link}}">{{job.title.title()}}</a></h3>
			<p class="r_city">  <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> {{job.location.title()}}</p>
			<span class = "r_description">{{job.description[0:390]}}</span> .... <br />

			<a id="lisa" class target="_blank" href="{{job.link}}"> More »</a>
        	{% endfor %}


			<br/>

				<span style="color:#91BD5A; font-size:15px; padding-right:20px;">
					Pages: <ul class="pagination">
					{%- for page in jobs.iter_pages() %}
					{% if page %}

      				{% if page != jobs.page %}
						{% if lang == "ee" %}
					       <a href="{{ url_for('estonia.result', page=page, title=title.lower(), location=location.lower()) }}">{{ page }}</a>
						{% else %}
        					<a href="{{ url_for('home.result', page=page, title=title.lower(), location=location.lower()) }}">{{ page }}</a>
						{% endif %}
      				{% else %}
       				 <strong>{{page}}</strong>
      				{% endif %}
    				{% else %}
      					<span class=ellipsis>…</span>

    				{% endif %}

					</ul>
  					{%- endfor %}

				</ul>
				</span>

			<div class="googleAd">
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- Ziliot Ad Unit-One -->
			<ins class="adsbygoogle"
     			style="display:inline-block;width:728px;height:90px"
     			data-ad-client="ca-pub-8929212152191613"
     			data-ad-slot="1240925074"></ins>
			<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
			</div><!-- end div Google ad -->

        </div>
        
        <div class="col-xs-3">
        	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- ziliot ad unit 2 -->
		<ins class="adsbygoogle"
			style="display:block"
			data-ad-client="ca-pub-8929212152191613"
			data-ad-slot="7373027075"
			data-ad-format="auto"></ins>
		<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
        	
        	
        </div>
        
        </div>

      </div> <!-- end row -->

{% endblock %}

templates/resultsEstonia.html
{% extends "custom_base.html" %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/local.css') }}">

	{% block title %} Löydä {{title}} Avoimet Työpaikat {{location}} {% endblock %}


	{%- block metas %}
		    <meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Löydä {{title}} Avoimet Työpaikat {{location}}">
    {%- endblock %}

{% block page_content %}

<div class="container">
	
	<div class="row">
		<div class="col-xs-1">
			
			
		</div>
		
		<div class="col-xs-8">
			<div class="r_searcher">


				<form action = "{{ url_for('estonia.searchEstonia') }}" method=post>
				<div class="r_div_input1">
					<label for="r_job_input">Mis?</label>
					<br />
					<input type="text" id="r_job_input" name="title" value="{{title}}" />
					<span id="input_help">nt. töö, firma pealkiri kus?</span>
				</div>
		
				<div class="r_div_input1">
					<label for="r_where_input">Kus?</label>
					<br />
					<input type="text" id="r_where_input" name="location" value="{{location}}" onfocus="document.getElementById('ui-id-1').style.display='block';" />
					<span id="input_help">nt. töö, firma pealkiri kus?</span>
				</div>
				
				<div class="div_submit1">
					<input type="submit" value="" class="r_subm1" />
				</div>
			</form>
		</div>
			
			
		</div>
		
		<div class="col-xs-3">
			
			
		</div>
		
		
		
	</div>


				
		<div class="row">
					
       <div class="col-xs-1">
       	
        	
        	
        </div>

        <div class="col-xs-8">
			{% for job in jobs.items %}
        	<h3 ><a class = "r_title" target="_blank" href="{{job.link}}">{{job.title.title()}}</a></h3>
			<p class="r_city">  <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> {{job.location.title()}}</p>
			<span class = "r_description">{{job.description[0:390]}}</span> .... <br />

			<a id="lisa" class target="_blank" href="{{job.link}}"> Rohkem »</a>
        	{% endfor %}


			<br/>

				<span style="color:#91BD5A; font-size:15px; padding-right:20px;">
					Lehed: <ul class="pagination">
					{%- for page in jobs.iter_pages() %}
					{% if page %}

      				{% if page != jobs.page %}
        			<a href="{{ url_for('estonia.result', page=page, title=title.lower(), location=location.lower()) }}">{{ page }}</a>
      				{% else %}
       				 <strong>{{page}}</strong>
      				{% endif %}
    				{% else %}
      					<span class=ellipsis>…</span>

    				{% endif %}

					</ul>
  					{%- endfor %}

				</ul>
				</span>

			<!------------Google Ads------------------>
		<div class="googleAd">
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- Ziliot Ad Unit-One -->
			<ins class="adsbygoogle"
     			style="display:inline-block;width:728px;height:90px"
     			data-ad-client="ca-pub-8929212152191613"
     			data-ad-slot="1240925074"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
		</div>

	<!---------------Google_ads------------->

        </div>
        
        <div class="col-xs-3">
        	
        	       	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- ziliot ad unit 2 -->
			<ins class="adsbygoogle"
			style="display:block"
			data-ad-client="ca-pub-8929212152191613"
			data-ad-slot="7373027075"
			data-ad-format="auto"></ins>
		<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
		</script>

        	
        </div>
        
        </div>

      </div> <!-- end row -->

{% endblock %}

templates/resultsFinnish.html
{% extends "custom_base.html" %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/local.css') }}">

	{% block title %} Löydä {{title}} Avoimet Työpaikat {{location}} {% endblock %}


	{%- block metas %}
		    <meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Löydä {{title}} Avoimet Työpaikat {{location}}">
    {%- endblock %}

{% block page_content %}

<div class="container">
	
	<div class="row">
		<div class="col-xs-1">
			
			
		</div>
		
		<div class="col-xs-8">
			<div class="r_searcher">


				<form action = "{{ url_for('home.search') }}" method=post>
				<div class="r_div_input1">
					<label for="r_job_input">Mitä?</label>
					<br />
					<input type="text" id="r_job_input" name="title" value="{{title}}" />
					<span id="input_help">esim. työ, yritys, otsikko</span>
				</div>
		
				<div class="r_div_input1">
					<label for="r_where_input">Missä?</label>
					<br />
					<input type="text" id="r_where_input" name="location" value="{{location}}" onfocus="document.getElementById('ui-id-1').style.display='block';" />
					<span id="input_help">esim. kaupunki</span>
				</div>
				
				<div class="div_submit1">
					<input type="submit" value="" class="r_subm1" />
				</div>
			</form>
		</div>
			
			
		</div>
		
		<div class="col-xs-3">
			
			
		</div>
		
		
		
	</div>


				
		<div class="row">
					
       <div class="col-xs-1">
       	
        	
        	
        </div>

        <div class="col-xs-8">
			{% for job in jobs.items %}
        	<h3 ><a class = "r_title" target="_blank" href="{{job.link}}">{{job.title.title()}}</a></h3>
			<p class="r_city">  <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> {{job.location.title()}}</p>
			<span class = "r_description">{{job.description[0:390]}}</span> .... <br />

			<a id="lisa" class target="_blank" href="{{job.link}}"> Lisää »</a>
        	{% endfor %}


			<br/>

				<span style="color:#91BD5A; font-size:15px; padding-right:20px;">
					Sivut: <ul class="pagination">
					{%- for page in jobs.iter_pages() %}
					{% if page %}

      				{% if page != jobs.page %}
        			<a href="{{ url_for('home.result', page=page, title=title.lower(), location=location.lower()) }}">{{ page }}</a>
      				{% else %}
       				 <strong>{{page}}</strong>
      				{% endif %}
    				{% else %}
      					<span class=ellipsis>…</span>

    				{% endif %}

					</ul>
  					{%- endfor %}

				</ul>
				</span>

			<!------------Google Ads------------------>
		<div class="googleAd">
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- Ziliot Ad Unit-One -->
			<ins class="adsbygoogle"
     			style="display:inline-block;width:728px;height:90px"
     			data-ad-client="ca-pub-8929212152191613"
     			data-ad-slot="1240925074"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
		</div>

	<!---------------Google_ads------------->

        </div>
        
        <div class="col-xs-3">
        	
        	       	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- ziliot ad unit 2 -->
			<ins class="adsbygoogle"
			style="display:block"
			data-ad-client="ca-pub-8929212152191613"
			data-ad-slot="7373027075"
			data-ad-format="auto"></ins>
		<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
		</script>

        	
        </div>
        
        </div>

      </div> <!-- end row -->

{% endblock %}

templates/searcher.html
{% extends "custom_base.html" %}

{% block title %} ziliot jobs {{ username }} {% endblock %}


{% block page_content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/local.css') }}">
<div class="container">
	
	<div class="row search_jobs">
            <div class="col-xs-2">
            </div>
            <div class="col-xs-8">
				            <h1>Search Jobs & Get Hired!</h1>
            </div>
            <div class="col-xs-2">
           </div>
      	</div>
	<div class="row">
    
			
<div class="col-xs-2">
            </div>
<div class="col-xs-3">
				{% if lang == "ee" %}
					<form action = "{{ url_for('estonia.search') }}" method=post>
				{% else %}
						<form action = "{{ url_for('home.search') }}" method=post>
				{% endif %}
				<div id="div_input1" class="div_input1">
					<label for="job_input">What</label>
					<br />
					<input type="text" id="job_input" name="title" />
					<span id="input_help">e.g. job, company, title</span>
				</div>
	</div>
<div class="col-xs-3">

	
				<div class="div_input1">
					<label for="where_input">Where</label>
					<br />
					<input type="text" id="where_input" name="location" onfocus="document.getElementById('ui-id-1').style.display='block';" />
					<span id="input_help">e.g. city, country</span>
				</div>
				
			</div>

		  <div class="col-xs-1">
			<div class="div_submit1">
					<input type="submit" value="" class="subm1" />
				</div>
			</form>
            </div>
            <div class="col-xs-3">
            </div>
		</div>
		
		<div class="row">
            <div class="col-xs-4">
            </div>
            <div class="col-xs-5">
            	<h3><a class="add" id="add_cv" >Add CVs</a></h3>
            	          

            <h3><a class="add" id="add_jobs" href="{{url_for('company.create_job')}}">Post jobs</a></h3>

 
            </div>
            <div class="col-xs-5">
           </div>
      	</div>
	</div>
	</div>
{% endblock %}

templates/searcher_estonia.html
{% extends "custom_base.html" %}

{% block title %} ziliot jobs {{ username }} {% endblock %}


{% block page_content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/local.css') }}">
<div class="container">
	
	<div class="row search_jobs">
            <div class="col-xs-2">
            </div>
            <div class="col-xs-8">
				            <h1>Leia Tööpakkumised siit! </h1>
            </div>
            <div class="col-xs-2">
           </div>
      	</div>
	<div class="row">
    
			
<div class="col-xs-2">
            </div>
<div class="col-xs-3">
				<form action = "" method=post>
				<div id="div_input1" class="div_input1">
					<label for="job_input">Mis? </label>
					<br />
					<input type="text" id="job_input" name="title" />
					<span id="input_help">nt. töö, firma pealkiri kus?</span>
				</div>
	</div>
<div class="col-xs-3">

	
				<div class="div_input1">
					<label for="where_input">Kus?</label>
					<br />
					<input type="text" id="where_input" name="location" onfocus="document.getElementById('ui-id-1').style.display='block';" />
					<span id="input_help">nt. linna</span>
				</div>
				
			</div>

		  <div class="col-xs-1">
			<div class="div_submit1">
					<input type="submit" value="" class="subm1" />
				</div>
			</form>
            </div>
            <div class="col-xs-3">
            </div>
		</div>
		
		<div class="row">
            <div class="col-xs-4">
            </div>
            <div class="col-xs-5">
            <h3><a class="add" id="add_cv" href="#">Lisa CVs</a></h3>


            <h3><a class="add" id="add_jobs"  href="{{url_for('company.create_job')}}">Uute töökohtade loomine</a></h3>

 
            </div>
            <div class="col-xs-5">
           </div>
      	</div>
	</div>
	</div>
{% endblock %}